/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

public class App {
    public String getGreeting(String[] args) {
        StringBuilder sb = new StringBuilder();
        for(String arg : args) {
            sb.append(arg + "\n");
        }
        return "Hello World!" + sb.toString();
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting(args));
    }
}
